### ISSUE TITLE
URLSearchParams is not defined at runtime

### ISSUE THREAD

**Issue by lionep** [bokub/linky-cli#1]
Nice tool !
I've an issue when running it from CLI :

```
# linky day
? What is your client area e-mail? mail@example.com
? What is your client area password? [hidden]
✖ Cannot retrieve consumption
ReferenceError: URLSearchParams is not defined
```

The package is installed globally, with node 8.12.0 and npm 6.4.1.

If you have any hint about this ?

**Comment by bokub** [comment]
Looks like it's a problem with this [line](https://github.com/bokub/linky/blob/edbba8f2a82f440235ced564b204f4920b10f4bc/index.js#L9).

According to the Node.js documentation, `URLSearchParams` is available on the global object in node 10 but not in earlier version.

I'm fixing it and adding tests on old node versions.

**Comment by bokub** [comment]
Please run `npm i -g linky-cli` again, then `linky --version` to be sure you have the **1.1.1**

The problem should be fixed now

**Comment by lionep** [comment]
Perfect!
It works fine now, thanks !
