### ISSUE TITLE
Credentials configuration file

### ISSUE THREAD

**Issue by franky47** [bokub/linky-cli#2]
At the moment credentials have to be supplied for every call of the program, either interactively (repetition) or through command-line arguments (shows up in bash history).

A nice way to automate queries would be either a configuration file or environment variables for the credentials.

**Comment by bokub** [comment]
Why don't you use your env variables **in** the CLI args? No repetition, and no bash history!

```sh
linky -u $LINKY_USER -p $LINKY_PSWD
```

**Comment by franky47** [comment]
Fair point, thanks !
