### ISSUE TITLE
Sauvegarde impossible

### ISSUE THREAD

**Issue by theofaucher** [bokub/linky-cli#3]
Bonsoir,

Je m'intérresse au compteur Linky et je viens de tomber sur votre dépot ! J'ai voulu essayer votre programme tout fonctionne sauf la sauvegarde du fichier des consomations. Est-ce normal ? Si non, si cela ne vous dérange pas, pourriez-vous regarder ce problème ?

Merci d'avance,
Faucher Théo

**Comment by bokub** [comment]
Bonjour Théo, 
C'est possible d'avoir plus de détails sur la commande lancée et le problème rencontré ?

**Comment by theofaucher** [comment]
Aaaaah je suis désolé, j'ai mal lu les commentaires dans le index.js .. Maintenant ça fonctionne sans aucun problème ! Merci de votre réponse !
